[package]
name = "surf-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arboard.workspace = true
directories.workspace = true
glutin.workspace = true
glutin-winit.workspace = true
image.workspace = true
imgui.workspace = true
imgui-glow-renderer.workspace = true
imgui-winit-support.workspace = true
raw-window-handle.workspace = true
surf-client-app.workspace = true
surf-core.workspace = true
surf-media.workspace = true
surf-protocol.workspace = true
surf-session.workspace = true
serde_json.workspace = true

[[bin]]
name = "surf-client"
path = "src/main.rs"
